import assert from "node:assert/strict";
import { test } from "node:test";
import canonicalizeTransformParams from "@/utils/canonicalizeTransformParams";

/**
 * The expected strings below were generated by running the API's own
 * canonicalizeTransformParams (dreep_server/src/services/sharp) — they are not
 * derived from this implementation. If one of these fails, the SDK and the API
 * disagree and every signed URL carrying that transform will 401.
 */

test("snaps width up to the next breakpoint", () => {
  const canonical = canonicalizeTransformParams({
    transform: { format: "webp", width: 803 },
  });

  assert.equal(JSON.stringify(canonical), '{"format":"webp","width":828}');
});

test("snaps width, height, quality and dpr in the API's key order", () => {
  const canonical = canonicalizeTransformParams({
    transform: { quality: 80, dpr: 2, width: 400, height: 300, fit: "cover" },
  });

  assert.equal(
    JSON.stringify(canonical),
    '{"width":512,"height":384,"fit":"cover","quality":75,"dpr":2}',
  );
});

test("serialises to an empty object when nothing was set", () => {
  const canonical = canonicalizeTransformParams({ transform: {} });

  assert.equal(JSON.stringify(canonical), "{}");
});

test("key order is fixed regardless of the order fields were given in", () => {
  const one = canonicalizeTransformParams({
    transform: { width: 400, format: "webp", quality: 90 },
  });
  const two = canonicalizeTransformParams({
    transform: { quality: 90, format: "webp", width: 400 },
  });

  assert.equal(JSON.stringify(one), JSON.stringify(two));
});
